### ISSUE TITLE
Link twitter in BotinfoCommand.java

### ISSUE THREAD

**Issue by duncte123** [DuncteBot/SkyBot#110]
Add a link to the [twitter account](https://twitter.com/DuncteBot) somewhere in the embed that is being sent.

[Link to file](https://github.com/DuncteBot/SkyBot/blob/a190bce76ddf3c928ab1cdc5de0971c1e971e89d/src/main/java/ml/duncte123/skybot/commands/uncategorized/BotinfoCommand.java#L91)

**Comment by GledsonAfonso** [comment]
Can I take this?

**Comment by duncte123** [comment]
Go ahead

**Comment by GledsonAfonso** [comment]
Thanks!

**Comment by GledsonAfonso** [comment]
How can I test the it? I saw that, for the moment, there's no self-hosting.

**Comment by duncte123** [comment]
If you run with --gen it will create a config, some values need to be set to empty strings, others can remain null

**Comment by GledsonAfonso** [comment]
@duncte123 I think I'm doing something wrong here. I tried using this as a parameter in the gradle run command, but it gives me an "Unknown command-line option '--gen'" error. Could you help me on this? I already have the commit ready, since is such a small feature, but I would like to test it first.

**Comment by duncte123** [comment]
It's a program argument, or alternatively you could run the gen method in the SkyBot class

**Comment by GledsonAfonso** [comment]
@duncte123 I see. I will try it when I get off from work. Thanks!

**Comment by duncte123** [comment]
Any updates on this?
